// vue-music/src/views/detail/Detail.vue
<template>
    <div class="detail">
      <common-my-scroll :className="'detail_wrapper'">
        <template #content>
          <detail-song-head :songHead="songHead"/>
          <detail-succinct :succinct="succinct"/>
          <detail-list :list="list"/>
        </template>
      </common-my-scroll>
    </div>
</template>

<script>
// 引入对应的API接口请求函数和数据整合函数
import { DetailSong, DetailSongHeadData, DetailSuccinctData, DetailSongList } from '../../api/detail'
// 引入适用性比较高的组件
import CommonMyScroll from '../../components/common/MyScroll'
// 引入当前组件模块下面的子组件
import DetailSongHead from './base/SongHead'
import DetailSuccinct from './base/Succinct'
import DetailList from './base/List'
export default {
  name: 'Detail',
  data () {
    return {
      songHead: {}, // 歌单详情头部数据
      succinct: {}, // 歌单简绍数据
      list: [] // 歌曲列表数据
    }
  },
  // 请求对应的数据
  created () {
    this.getData()
    localStorage.setItem('search', window.location.search)
  },
  methods: {
    // 请求对应的函数
    async getData () {
      // 解构我们需要使用的数据
      const { playlist } = await DetailSong(this.$route.query.id)
      // 整合头部的数据
      this.songHead = new DetailSongHeadData(playlist.coverImgUrl, playlist.name)
      // 整合简绍部分的数据
      this.succinct = new DetailSuccinctData(playlist.tags, playlist.description)
      // 整合歌曲列表部分的数据
      playlist.tracks.length = 25 // 限制请求完成返回来数组的length长度
      this.list = new DetailSongList(playlist.tracks).list
    }
  },
  components: {
    CommonMyScroll,
    DetailSongHead,
    DetailSuccinct,
    DetailList
  }
}
</script>

<style scoped lang="scss">
  .detail {
    background-color: #F8F8F8;
  }
</style>

// react-music/src/views/detail/Detail.js
import React, {Component} from 'react'
import Url from 'url'
// 引入对应的API请求函数
import {DetailSongData, DetailSongHeadData,DetailSuccinctData, DetailSongListData} from '../../api/detail'
// 引入适用性比较搞的组件
import CommonGoBack from '../../component/common/GoBack'
import CommonMyScroll from '../../component/common/MyScroll'
// 引入当前组件下面的子组件
import DetailBannerHead from "./base/BannerHead";
import DetailSuccinctIcon from './base/SuccinctIcon'
import DetailSongList from './base/SongList'
class Detail extends Component {
    state = {
        SongHead: {}, // 歌单头部数据
        SuccinctIcon: {}, // 歌曲简绍数据
        SongList: [] // 歌曲列表
    }
    // 在组件没有被挂载的时候 我们进行请求数据
    componentDidMount() {
        this.getData()
    }
    // 请求数据的函数
    async getData () {
        // 使用url获取到query的属性值
        const id = Url.parse(this.props.location.search, true).query.id
        // 解构我们过来的数据
        const {playlist: {coverImgUrl, name, tags, description, tracks}} = await DetailSongData(id)
        const {list} = new DetailSongListData(tracks)
        list.length = 25 // 限制数组的长度
        this.setState({
            // 整合头部数据 并且更改对应的状态
            SongHead: new DetailSongHeadData(coverImgUrl, name),
            // 整合简绍歌曲数据 并且修改对应的状态
            SuccinctIcon: new DetailSuccinctData(tags, description),
            // 整合歌曲列表数据 并且修改对应的状态
            SongList: list
        })
    }
    // 编导式导航到上一个历史页面
    handleClick = () => {
        this.props.history.go(-1)
    }
    render() {
        // 解构state状态管理当中的数据
        const {SongHead, SuccinctIcon, SongList} = this.state
        // BScroll 需要滚动的区域
        const content = (
            <div className={"detail"}>
                <CommonGoBack handleClick={this.handleClick}/>
                <DetailBannerHead SongHead={SongHead}/>
                <DetailSuccinctIcon SuccinctIcon={SuccinctIcon}/>
                <DetailSongList SongList={SongList}/>
            </div>
        )
        return (
            <CommonMyScroll content={content} className={"detail_wrapper"}/>
        )
    }
}

export default Detail
