// react-hook-music/src/views/HotSong/HotSong.js
import React, {useState, useEffect} from "react";
// 引入对应的css样式
import '../../style/hotsong.scss'
// 引入对应的api请求函数
import {BannerData} from '../../api/hotsong'
// 引入对应的工具类函数
import conformityData from '../../utils/conformity'
// 引入适用性比较高的组件
import CommonMyScroll from '../../component/common/MyScroll'
// 引入当前模块下面的子组件
import HotSongBanner from './base/Banner'
import HotSongList from './base/SongList'
function HotSong () {
    // banner标题文字
    const [description, setDescription] = useState('更新日期：4月18日')
    // 热门榜的歌曲列表数据
    const [tracks, setTracks] = useState([])
    // 请求数据的函数
    const getData = async () => {
        // 解构出来请求的数据
        const {playlist: {description, tracks}} = await BannerData(1)
        setDescription(description) // banner文字数据
        // 热门榜的歌曲列表数据
        tracks.length = 25
        setTracks(conformityData(tracks));
    }
    // 请求数据
    useEffect(() => {
        getData()
    }, [])
    // 需要滚动的内容
    const content = (
        <div className={"hotsong"}>
            <HotSongBanner description={description}/>
            <HotSongList tracks={tracks}/>
        </div>
    )
    if (tracks.length) {
        return <CommonMyScroll content={content} className={"wrapper_hotsong"}/>
    } else  {
        return <div></div>
    }
}

export default HotSong

// vue-music/src/views/hotsong/HotSong.vue
<template>
  <div class="hotsong">
    <common-my-scroll :className="'hotsong_wrapper'">
      <template #content>
        <hot-song-banner :description="description"/>
        <hot-song-list :tracks="tracks"/>
      </template>
    </common-my-scroll>
  </div>
</template>

<script>
// 引入对应的API接口请求函数
import { hotSongData } from '../../api/hotsong'
// 引入工具类函数用于整合数据
import { ConformityDetailData } from '../../utils/conformitydata'
// 引入适用性比较好的组件
import CommonMyScroll from '../../components/common/MyScroll'
// 引入当前模块下面的子组件
import HotSongBanner from './base/Banner'
import HotSongList from './base/List'
export default {
  name: 'HotSong',
  data () {
    return {
      description: '', // 标题
      tracks: [] // 热歌榜列表数据
    }
  },
  // 请求对应的数据
  created () {
    this.getHotSongData()
  },
  methods: {
    // 请求数据的函数方法
    async getHotSongData () {
      const { playlist: { description, tracks } } = await hotSongData(1)
      this.description = description
      tracks.length = 25 // 显示数组的长度
      this.tracks = ConformityDetailData(tracks)
    }
  },
  components: {
    CommonMyScroll,
    HotSongBanner,
    HotSongList
  }
}
</script>

<style scoped lang="scss">
  .hotsong {
    padding-top: 108px;
  }
</style>
